//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kk.CodeTemplates
{
    using System;
    
    public partial class NombreDetalle
    {
        public string Title { get; set; }
        public string Nombre { get; set; }
        public string MiddleName { get; set; }
        public string Apellidos { get; set; }
    }
}
